const UUID_DEFAULT = `(lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))))`

export const createSQLStatements = [
    `CREATE TABLE IF NOT EXISTS USUARIO (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        NOME TEXT,
        EMAIL TEXT,
        ID_CEDE INTEGER,
        ID_IMAGEM_PERFIL_USUARIO INTEGER,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS PLANEJAMENTO (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        ID_CIDADE INTEGER,
        ID_CATEGORIA INTEGER,
        NOME TEXT,
        ATIVIDADE INTEGER,
        TIPO INTEGER,
        DATA_ULT_VISITA DATETIME,
        ANO DATE,
        ZONA TEXT,
        STATUS INTEGER,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS CIDADE (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        NOME TEXT,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS CATEGORIA (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        NOME TEXT,
        SITUACAO INTEGER
    );`,
     
    `CREATE TABLE IF NOT EXISTS ENDERECO (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        NOME TEXT,
        ID_CIDADE INTEGER,
        CEP TEXT,
        NUMERO TEXT,
        LADO TEXT,
        TIPO_IMOVEL TEXT,
        COMPLEMENTO TEXT,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS VISITA (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        ID_ENDERECO INTEGER,
        ID_PLANEJAMENTO INTEGER,
        PRIMEIRA_VISITA DATETIME,
        SEGUNDA_VISITA DATETIME,
        TIPO_VISITA TEXT,
        NUMERO_QUARTOS TEXT,
        CONTEM_AMOSTRA BOOL,
        CONTEM_TRATAMENTO BOOL,
        SITUACAO_REFERENCIA INTEGER,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS INSPECAO (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        ID_VISITA INTEGER,
        ID_INSPECAO_DETALHE INTEGER,
        NUMERO_DEPOSITOS INTEGER,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS INSPECAO_DETALHE (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        DESCRICAO TEXT,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS AMOSTRA (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        ID_VISITA INTEGER,
        NUMERO_INICIO INTEGER,
        NUMERO_FINAL INTEGER,
        QUANTIDADE INTEGER,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS IMAGEM_AMOSTRA (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        ID_AMOSTRA INTEGER,
        NOME TEXT,
        IMAGEM BLOB,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS TRATAMENTO (
        ID CHAR(36) DEFAULT ${UUID_DEFAULT} PRIMARY KEY,
        ID_VISITA INTEGER,
        DEPOSITOS_ELIMINADOS INTEGER,
        IMOVEIS_TRATADOS INTEGER,
        QTD_TRATAMENTO INTEGER,
        TIPO TEXT,
        QTD_CARGA INTEGER,
        SITUACAO INTEGER
    );`,

    `CREATE TABLE IF NOT EXISTS TABLES_SINCRONYZE (
        ID INTEGER PRIMARY KEY,
        TABELA TEXT,
        ID_REGISTRO TEXT
    );`,
  ];
  